import { Navbar } from '@/Components/Navbar/Navbar'
import Head from 'next/head'

export default function Home() {
    return (
        <>
        <Head>
            <title> Caminhos do Sabor</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
        </Head>
        <div className='w-full max-w-[1120px] flex flex-col mx-auto pb-12'>
           <Navbar/>
        </div>
        </>
    )
}
